[widgets]
[widgets.topbar]
route = ""
width = "100%"
height = "50%"
layer = "top"
anchor = ["top", "left", "right"]
monitors = [0, 1]
exclusivity = true
exclusivity_zone = 50
click_regions = [
    { name = "bar", x = "0", y = "0", width = "100%", height = "50" },
]
hidden = false

[widgets.notification-center]
route = "/notification-center"
width = "500"
height = "400"
layer = "top"
anchor = ["top", "right"]
monitors = [0]
exclusivity = false
click_regions = []
margin_top = "20"
margin_right = "20"
hidden = false