[widgets]
[widgets.topbar]
route = ""
width = "100% - 70"
height = "800"
layer = "top"
anchor = ["top", "left", "right"]
monitors = [0, 1]
exclusivity = true
exclusivity_zone = 50
click_regions = [
    { name = "bar", x = "0", y = "0", width = "100%", height = "300" },
]
hidden = false